size: 640
translation_probability: 0.5
translation_amplitude: 0.1
rotation_probability: 0.5
rotation_amplitude: 45
scaling_probability: 0.5
scaling_amplitude: 0.1
stretching_probability: 0.5
stretching_amplitude: 0.1
shearing_probability: 0.5
shearing_amplitude: 0.1
vertical_flip_probability: 0.5
horizontal_flip_probability: 0.5
monochrome_probability: 0.5
hue_probability: 0.5
hue_amplitude: 0.01
saturation_probability: 0.5
saturation_amplitude: 0.1
brightness_probability: 0.5
brightness_amplitude: 0.1
contrast_probability: 0.5
contrast_amplitude: 0.1
sharpness_probability: 0.5
sharpness_amplitude: 0.1