log_level: 

checkpoint: 
input_size: 352
train_path: ./dataset/RLB_dataset/train
test_path: ./dataset/RLB_dataset/test
epochs: 300
batch_size: 96
learning_rate: 0.001
milestones:
  - 100
  - 200
  - 250
num_workers: 8

iou_threshold: 0.5
confidence_threshold: 0.5

class_id_offset: -80
classes:
- robot
- turret
- obstacle

augmentation:
  translation_probability: 0.25
  translation_amplitude: 0.25
  rotation_probability: 0.25
  rotation_amplitude: 45
  scaling_probability: 0.25
  scaling_amplitude: 0.5
  stretching_probability: 0.25
  stretching_amplitude: 0.25
  shearing_probability: 0.25
  shearing_amplitude: 0.1
  vertical_flip_probability: 0.25
  horizontal_flip_probability: 0.25
  monochrome_probability: 0.5
  hue_probability: 0.25
  hue_amplitude: 0.25
  saturation_probability: 0.25
  saturation_amplitude: 0.25
  brightness_probability: 0.25
  brightness_amplitude: 0.25
  contrast_probability: 0.25
  contrast_amplitude: 0.25
  sharpness_probability: 0.25
  sharpness_amplitude: 0.25