log_level: 

checkpoint: 
input_size: 320
train_path: ./dataset/train
test_path: ./dataset/test
epochs: 300
batch_size: 128
learning_rate: 0.001
# milestones:
#   - 100
#   - 200
#   - 250
milestones:
  - 50
  - 100
  - 150
num_workers: 8
  
classes:
- person
- bicycle
- car
- motorcycle
- airplane
- bus
- train
- truck
- boat
- traffic light
- fire hydrant
- stop sign
- parking meter
- bench
- bird
- cat
- dog
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard
- sports ball
- kite
- baseball bat
- baseball glove
- skateboard
- surfboard
- tennis racket
- bottle
- wine glass
- cup
- fork
- knife
- spoon
- bowl
- banana
- apple
- sandwich
- orange
- broccoli
- carrot
- hot dog
- pizza
- donut
- cake
- chair
- couch
- potted plant
- bed
- dining table
- toilet
- tv
- laptop
- mouse
- remote
- keyboard
- cell phone
- microwave
- oven
- toaster
- sink
- refrigerator
- book
- clock
- vase
- scissors
- teddy bear
- hair drier
- toothbrush
- robot
- turret
- obstacle

augmentation:
  translation_probability: 0.25
  translation_amplitude: 0.1
  rotation_probability: 0.25
  rotation_amplitude: 45
  scaling_probability: 0.25
  scaling_amplitude: 0.1
  stretching_probability: 0.25
  stretching_amplitude: 0.1
  shearing_probability: 0.25
  shearing_amplitude: 0.1
  vertical_flip_probability: 0.25
  horizontal_flip_probability: 0.25
  monochrome_probability: 0.1
  hue_probability: 0.25
  hue_amplitude: 0.1
  saturation_probability: 0.25
  saturation_amplitude: 0.1
  brightness_probability: 0.25
  brightness_amplitude: 0.1
  contrast_probability: 0.25
  contrast_amplitude: 0.1
  sharpness_probability: 0.25
  sharpness_amplitude: 0.1