augmentation:
  brightness_amplitude: 0.25
  brightness_probability: 0.25
  contrast_amplitude: 0.25
  contrast_probability: 0.25
  horizontal_flip_probability: 0.25
  hue_amplitude: 0.1
  hue_probability: 0.25
  monochrome_probability: 0.5
  rotation_amplitude: 45
  rotation_probability: 0.25
  saturation_amplitude: 0.25
  saturation_probability: 0.25
  scaling_amplitude: 0.5
  scaling_probability: 0.25
  sharpness_amplitude: 0.25
  sharpness_probability: 0.25
  shearing_amplitude: 0.1
  shearing_probability: 0.25
  stretching_amplitude: 0.25
  stretching_probability: 0.25
  translation_amplitude: 0.25
  translation_probability: 0.25
  vertical_flip_probability: 0.25
batch_size: 96
checkpoint: null
class_id_offset: -80
classes:
- robot
- turret
- obstacle
coco2017_proportion: 0.0
coco2017_test_path: ./dataset/COCO2017_dataset/test
coco2017_train_path: ./dataset/COCO2017_dataset/train
confidence_threshold: 0.5
epochs: 300
input_size: 352
iou_threshold: 0.25
learning_rate: 0.001
log_level: null
milestones:
- 50
- 100
- 150
- 200
- 250
num_workers: 8
pretrained: ./weights/weight_AP05_0.253207_280-epoch.pth
test_path: ./dataset/RLB_dataset/test
train_path: ./dataset/RLB_dataset/train
